language: node_js
node_js:
  - 'node'
  - 'lts/*'

jobs:
  include:
    - stage: lint & codecov
      node_js: node
      script:
        - npm run lint
        - npm install -g codecov
        - npx jest --coverage
        - codecov
